/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_landsem_jnistudy_TestManager */

#ifndef _Included_com_gome_gometestyuv_TestManager
#define _Included_com_gome_gometestyuv_TestManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gome_gometestyuv_TestManager
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gome_gometestyuv_TestManager_nativeInit(JNIEnv *env, jclass);

/*
 * Class:     com_gome_gometestyuv_TestManager
 * Method:    nativeAdd
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_gome_gometestyuv_TestManager_nativeAdd(JNIEnv *env, jclass, jint num1, jint num2);

/*
 * Class:     com_gome_gometestyuv_TestManager
 * Method:    nativeMergeJpg2Yuv
 * Signature: (II)I
 */
JNIEXPORT jbyteArray JNICALL Java_com_gome_gometestyuv_TestManager_nativeMergeJpg2Yuv(JNIEnv *env, jclass, jstring jpeg_path,jint width_small,jint height_small,jbyteArray camera_buff,jint width_big,jint height_big);

#ifdef __cplusplus
}
#endif
#endif
